### PR TITLE
Restrict dropdown choices

### LINKED ISSUE #72: Filter fields to limit dropdown options
**Problem:** Currently some filter dropdown menus include entries that are private and should not be visible to the logged in user. This is not a big issue, as all the user can see is the string representation of the object, they still can't access the full entry, but it would be better if they were hidden. 

**Proposed solution:**
It is probably necessary to prefilter a queryset somewhere based on the logged in user. Possibly in `django_filters.filterset.BaseFilterSet.filter_queryset()`:

```python
 def filter_queryset(self, queryset):
        """
        Filter the queryset with the underlying form's `cleaned_data`. You must
        call `is_valid()` or `errors` before calling this method.

        This method should be overridden if additional filtering needs to be
        applied to the queryset before it is cached.
        """
        for name, value in self.form.cleaned_data.items():
            queryset = self.filters[name].filter(queryset, value)
            assert isinstance(queryset, models.QuerySet), \
                "Expected '%s.%s' to return a QuerySet, but got a %s instead." \
                % (type(self).__name__, name, type(queryset).__name__)
        return queryset
```

**Update: This is quite important. It may violate an NDA or similar agreement if even the name of a private device or batch is publicly visible.**

It may be that the filter itself can be suitably modified, but the logic will likely have to be added to the view, where there is knowledge of the logged in user. https://django-filter.readthedocs.io/en/stable/guide/usage.html#the-filter

Once we've figured out how to do it:

- [ ] Ensure that private entries are not shown in dropdown menus when filtering. 
- [ ] Remove AnonymousUser from dropdown options.

Aha! Link: https://imperial-college-ict.aha.io/requirements/RSE-132-15

### PR DESCRIPTION
**Pull request by dandavies99**
Restricts dropdown choices to those the user has permission for. 

This ensures that no private device specifications are listed as options in:
- The filter form when searching for batches
- The form for creating or updating new batches

I can't see any other places there could be a risk of this happening. 

Closes #72 (finally)

### CODE REVIEW

**Review by AdrianDAlessandro — COMMENTED** [review]
Not sure if this is related to this PR, but in trying to test this I tried to make a public and a private batch and selected "Module" as the specification for one of them and got the error: "Select a valid choice. That choice is not one of the available choices."

Then when I went to select another choice, "Module" was no longer there ("Module" is an abstract specification, if that helps)

**Comment by AdrianDAlessandro** [comment]
This doesn't address the "Remove AnonymousUser from dropdown options." test in #72

**Comment by dandavies99** [comment]
> Not sure if this is related to this PR, but in trying to test this I tried to make a public and a private batch and selected "Module" as the specification for one of them and got the error: "Select a valid choice. That choice is not one of the available choices."
> 
> Then when I went to select another choice, "Module" was no longer there ("Module" is an abstract specification, if that helps)

Yeah this is a bit annoying.

This is expected because `limit_choices_to={"abstract": False}` is set on the specification field of the `Batch()` class. 

I've tried explicitly setting `allowed_device_specs = allowed_device_specs.filter(abstract=False)` in the filter but it doesn't change the behaviour. 

For now, at least the form refreshes with a sensible message and reduced list of actually allowed device specs, but I'll flag this in a separate issue.

**Comment by dandavies99** [comment]
I had forgotten about the AnonymousUser appearing in the dropdowns issue, but that was an easy fix by modifying the BaseFilter ✅

**Comment by dandavies99** [comment]
> Secret Experiments (ie a private experiment that uses a public batch):

I don't think this is as much of an issue, but it depends how the experiment is named. The template has now been modified to check the experiment permissions before rendering each row. 

> Private batches when looking at public experiments (although this one seems like user-error)

Yeh we're getting into the boggy mires of how permissions of various objects should _propagate_. For simplicity, I've done the same as above and checked the permissions in the template for each batch when each row of the template is rendered.

**Comment by dandavies99** [comment]
Thanks for the thorough checks, @AdrianDAlessandro. Ready for another look 😉

**Review by AdrianDAlessandro — APPROVED** [review]
Great! Looks like this covers all the issues I commented on

**Pull request merged**
